### ISSUE TITLE
Unable to add .d.mts/.d.cts source files to ts_project

### ISSUE THREAD

**Issue by jstuder-gh** [aspect-build/rules_ts#121]
Currently users are unable to add `.d.mts`/`.d.cts` declaration source files to a `ts_project` target.

The following build omits the .`d.mts` file and subsequent targets relying on it's types will fail:

```starlark
ts_project(
    name = "lib_ts",
    srcs = [
        "index.ts",
        "lib_types.d.ts",
        "lib_types_2.d.mts",
    ],
    declaration = True,
)
```

```typescript
// index.ts
export * from './lib_types';
export * from './lib_types_2.mjs';
```

```typescript
// lib_types_2.d.mts
export type B = string;
```

**Comment by jstuder-gh** [comment]
Added PR addressing this here:

https://github.com/aspect-build/rules_ts/pull/122

**Comment by jbedard** [comment]
Fixed with https://github.com/aspect-build/rules_ts/pull/122
