### ISSUE TITLE
Extending a tsconfig.json with a dictionary fails

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_ts#124]
Hi,

I have the following in a root `BUILD.bazel` file:

```bazel
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:defs.bzl", "npm_link_all_packages")

ts_project(
    name = "index",
    srcs = [
        "index.ts",
    ],
    declaration = True,
    extends = ":tsconfig.json",
    tsconfig = {},
)

npm_link_all_packages(name = "node_modules")
```

On running `bazel build //:index` I get an error:

```
tsconfig_index.json(1,136): error TS6053: File 'tsconfig.json' not found.
```

Looking in the `bin` everything does seem to be in order, so I'm wondering if the working directory is incorrect maybe?

**Comment by paullewis** [comment]
Repro repo 😄 - https://github.com/paullewis/repro-rules-ts-issue-124

**Comment by alexeagle** [comment]
TypeScript needs the path to start with `./` in this case - when I add that the repro works. We have other examples using this pattern like https://github.com/aspect-build/rules_ts/blob/main/examples/extends_chain/main/BUILD.bazel#L14-L20 but they all resolve to a tsconfig in a parent folder (typical layout) so they start with `../` and it happens to work. 

Easy repro in rules_ts itself is just

```
diff --git a/examples/simple/BUILD.bazel b/examples/simple/BUILD.bazel
index 0bc457f..a75ab54 100644
--- a/examples/simple/BUILD.bazel
+++ b/examples/simple/BUILD.bazel
@@ -39,6 +39,7 @@ ts_project(
         "foo.ts",
         "generated.ts",
     ],
+    extends = "tsconfig.json",
     # A tsconfig.json file will be generated with this content
     tsconfig = {
         "compilerOptions": {
```

**Comment by alexeagle** [comment]
ah, this is actually documented behavior https://www.typescriptlang.org/tsconfig#extends
> The path may use Node.js style resolution.
so when it's just "tsconfig.json" the resolver will think that's an npm package name.

**Comment by paullewis** [comment]
Right, yes, you can have it resolve to a package in `node_modules` with a `tsconfig.json` to extend from. Which I suppose is what it'll attempt if it's not prefixed with `./` or similar.
