### ISSUE TITLE
rootDir not respected

### ISSUE THREAD

**Issue by pullard** [aspect-build/rules_ts#151]
Given `rootDir` (or lack thereof) is not respected during compilation, this essentially breaks relative paths that traverse outside of the current directory.

#### BUILD
```py
ts_project(
    name = "current-dir",
    srcs = ["current-dir.ts"],
    deps = [
        "//src/outside/root-dir",
        "//src/outside/current-dir/inside/root-dir",
    ],
    tsconfig = "//:tsconfig",
    ....
)
```

#### current-dir.ts
```ts
// works
import { something } from './inside/root-dir';
// fails with: somethingElse is outside of the configured 'rootDir'
import { somethingElse } from '../outside/root-dir';
```

#### tsconfig.json (@ root)
```json
{
  "compileOnSave": false,
  "exclude": ["bazel-*"],
  "compilerOptions": {
    "rootDir": "."
  }
}
```

This occurs because in `ts_project.bzl` it assigns `rootDir` via `_lib.calculate_root_dir(ctx)`:
https://github.com/aspect-build/rules_ts/blob/main/ts/private/ts_project.bzl#L62

`calculate_root_dir` essentially assigns `rootDir` to `package_name()` + given `ctx.attr.root_dir`

I would expect that `rootDir` should be *exactly* what is given in the `tsconfig.json` or omitted from the command if not provided.

**Comment by thesayyn** [comment]
AFAIK this is by design. Essentially, ts_project is a tsc wrapper that passed just enough information to make tsc behave the right way under bazel. If you omit `root_dir` attribute, then ts_project will generate one to prevent tsc from including anything outside of `rootDir` as a source. I believe this is the reason behind auto-generated `rootDir` but @alexeagle might know more. 



 

> I would expect that `rootDir` should be _exactly_ what is given in the `tsconfig.json` or omitted from the command if not provided.

This is not possible due to how bazel works. It is not possible to read files during analysis phase, therefore ts_project can't tell if the tsconfig.json has a `rootDir` already. that's why you have to provide the rootDir attribute.

**Comment by pullard** [comment]
> This is not possible due to how bazel works. It is not possible to read files during analysis phase, therefore ts_project can't tell if the tsconfig.json has a rootDir already. that's why you have to provide the rootDir attribute.

I see, makes sense but, explicitly setting `root_dir` just appends to the generated `rootDir` instead of replacing it

**Comment by jbedard** [comment]
> I see, makes sense but, explicitly setting root_dir just appends to the generated rootDir instead of replacing it

The `ts_project(root_dir)` gets appended to the directory of the `ts_project` rule (the directory of the BUILD file). So yes it is relative just like executing `tsc` in the folder of the BUILD. Bazel will have the extra restriction that the `rootDir` must still be within the directory that the BUILD owns - you can't tell `ts_project` to access files it does not own.

**Comment by jbedard** [comment]
rules_ts passes the `--rootDir` cli arg 100% of the time so the `tsconfig.json` `rootDir` and default inferred path will never be used.

The `ts_project(root_dir)` is relative to the BUILD its in just like the tsconfig one is relative to the tsconfig and `--rootDir` is relative to the cwd etc.

Note that `rootDirs` might do what you're trying to? Those 2 are different and very awkwardly named though.

**Comment by cgrindel** [comment]
@pullard Do you feel that your question has been answered?

**Comment by pullard** [comment]
Oh sorry, @cgrindel, yes this is satisfactory solution!
