### ISSUE TITLE
Worker does not find 3rd party deps with Bazel 6 --experimental_allow_unresolved_symlinks

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_ts#166]
In https://github.com/aspect-build/bazel-examples:

```shell
$ export USE_BAZEL_VERSION=last_green    
$ cd next.js
$ bazel run start --experimental_allow_unresolved_symlinks

INFO: Analyzed target //:start (0 packages loaded, 1550 targets configured).
INFO: Found 1 target...
ERROR: /Users/matt/Documents/GitHub/bazel-examples/next.js/pages/api/BUILD.bazel:5:11: Compiling TypeScript project @//pages/api:api_typings [tsc -p tsconfig.json] failed: (Exit 1): tsc_worker.sh failed: error executing command (from target //pages/api:api_typings) bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh @bazel-out/darwin-fastbuild/bin/pages/api/hello.d.ts-0.params

pages/api/hello.ts(2,54): error TS2307: Cannot find module 'next' or its corresponding type declarations.

**Comment by thesayyn** [comment]
the error looks like it has something to do with a bug recently fixed #169. 

does this only happen when `--experimental_allow_unresolved_symlinks` is present or only on`last_green`?

**Comment by matthewjh** [comment]
@thesayyn did you try to reproduce it using the instructions? I found this issue before you raised that bug fix, so I don't see how it could be related. Or are you saying that fix might fix this?

As far as I remember, this only happens --experimental_allow_unresolved_symlinks and last_green. Not last_green without --experimental_allow_unresolved_symlinks.

**Comment by thesayyn** [comment]
> As far as I remember, this only happens with both --experimental_allow_unresolved_symlinks and last_green. Not last_green without --experimental_allow_unresolved_symlinks.

then it is caused by how the symlinks are laid out in 6.x. I'll need to dig a little deep to determine how this can be fixed. 


> did you try to reproduce it using the instructions

I didn't have time to look into this one yet. I was just speculating to get more info.

**Comment by thesayyn** [comment]
update; there is a bug in bazel 6.x which needs to be fixed before this issue can be fixed.

**Comment by matthewjh** [comment]
Thanks @thesayyn, your fix is working well.
