### ISSUE TITLE
ts_project_workers should expose a way to find the logs of the worker

### ISSUE THREAD

**Issue by bhavitsharma** [aspect-build/rules_ts#196]
Logging is not straightforward in worker mode since Bazel's protocol uses stdin/out for communication. However, we should expose a method to add logs to a file that we can inspect. Note that this is different from the compiler host's log which should be called using `host.trace?`

**Comment by thesayyn** [comment]
related to #189

**Comment by thesayyn** [comment]
fixed by #264
