### ISSUE TITLE
[Bug]: Clarify if worker_sandboxing is supported

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_ts#206]
### What happened?

The /README says
Please note that rules_ts does not work with `--worker_sandboxing`.

If that's true, then it should probably link to a bug about why not.

### Version

HEAD

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by thesayyn** [comment]
See https://github.com/aspect-build/rules_ts/issues/127#issuecomment-1312041592
