### ISSUE TITLE
[Bug]: can't pass srcs to ts_project via another rule when transpiler is used

### ISSUE THREAD

**Issue by mattem** [aspect-build/rules_ts#219]
### What happened?

When using the `transpiler` attr on `ts_project`, it's not possible to pass `srcs` to the rule that are an output of another without referencing them by named output.

This is caused by the assumptions made in the `_is_ts_src` (and related methods) that it is working directly with labels that match source file names, https://github.com/aspect-build/rules_ts/blob/main/ts/private/ts_lib.bzl#L152-L162

### Version

HEAD

### How to reproduce
Apply the following patch:

```shell
diff --git a/examples/transpiler/BUILD.bazel b/examples/transpiler/BUILD.bazel
index d9e1ede..694333b 100644
--- a/examples/transpiler/BUILD.bazel
+++ b/examples/transpiler/BUILD.bazel
@@ -18,11 +18,16 @@ write_file(
     ],
 )

+filegroup(
+    name = "srcs",
+    srcs = ["big.ts"],
+)
+
 # Runs babel to transpile ts -> js
 # and tsc to type-check
 ts_project(
     name = "babel",
-    srcs = ["big.ts"],
+    srcs = [":srcs"],
     declaration = True,
     out_dir = "build-babel",
     source_map = True,
```

Then run:

```
$ bazel build //examples/transpiler:babel

INFO: Analyzed target //examples/transpiler:babel (1 packages loaded, 7 targets configured).
INFO: Found 1 target...
Target //examples/transpiler:babel up-to-date (nothing to build)
INFO: Elapsed time: 0.223s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

Note how bazel reports there is nothing to build.

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Discussed in stand-up.

Solution is to not pass `js_outs` and `map_outs` to the transpiler function.

Transpiler function is responsible for declaring its own predeclared outputs. This can only be done a transpiler macro and not possible if it a rule directly. Babel example will need to be updated to do this here: https://github.com/aspect-build/rules_ts/blob/main/examples/transpiler/babel.bzl#L6

Transpiler rules needs to filter out non `.ts` files. Requires a change in rules_swc here: https://github.com/aspect-build/rules_swc/blob/main/swc/private/swc.bzl#L140

**Comment by jbedard** [comment]
Babel example in rules_ts will need to be updated to not depend on the `js/map_outs`: https://github.com/aspect-build/rules_ts/blob/fe974b9255a1e777f62c157dfa07fc363c350225/examples/transpiler/babel.bzl#L25-L29
