### ISSUE TITLE
[Bug]: satisfies operator breaks ts_project builds

### ISSUE THREAD

**Issue by rc-glean** [aspect-build/rules_ts#256]
### What happened?

Is it safe to upgrade @npm_typescript to 4.9.* https://github.com/aspect-build/rules_ts/blob/9e03fd92eebec869b9c092272b421550a3c1c1f5/WORKSPACE#LL20-L20C22?

Is there a workaround that users can define in their workspaces in the meantime?

`bazel build //typescript/...`

`typescript/core/theme/Fonts.ts: error TS2304: Cannot find name 'satisfies'.`

### Version

`bazel run -- @npm_typescript//:tsc --version`

`Version 4.8.2`

### How to reproduce

```shell
Use satisfies operator in ts code
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by rc-glean** [comment]
Confirmed that directory_path here works in users' workspace

https://cs.github.com/aspect-build/rules_ts/blob/9e03fd92eebec869b9c092272b421550a3c1c1f5/ts/BUILD.typescript?q=%3Atsc_entrypoint#L23-L35

**Comment by alexeagle** [comment]
Yes, TS 4.9 should work, if your `bazel run -- @npm_typescript//:tsc --version` gives the old version then you just need to fix your `WORKSPACE`. maybe you don't have https://github.com/aspect-build/rules_ts/pull/251 ?

**Comment by rc-glean** [comment]
Thanks for confirming. This is not a bug, and it seems like it's standard to override rules_ts' TS version like so

https://cs.github.com/angular/vscode-ng-language-service/blob/b339166d1bd5dd18ac45b14fd03ec9fa2549b17c/WORKSPACE?q=rules_ts_dependencies%28ts_version_from#L21-L23

I was hoping that 4.9.* can become the default version, but that seems unsafe given there's [breaking changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-rc/#correctness-fixes-and-breaking-changes)

Feel free to close this issue. I think the linked angular code search is a good enough google'able workaround if anyone else runs up against wanting to switch the default rules_ts TS version

**Comment by alexeagle** [comment]
I would have hoped that the docs here https://github.com/aspect-build/rules_ts/blob/main/docs/repositories.md would answer the question, rather than having to discover what we did for Angular.

I'll update the copy-paste install snippet to make this a bit easier to find.
Also, since we named it `LATEST_VERSION` I think it's actually correct for it to drift as you update rules_ts, so it is now 4.9 - it changed in https://github.com/aspect-build/rules_ts/compare/v1.0.1...v1.0.2
