### ISSUE TITLE
[Bug]: ts_config doesn't provide a JsInfo

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/rules_ts#271]
See https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1670621678898069?thread_ts=1670620951.407769&cid=CEZUUKQ6P for more context

**Comment by gregmagolan** [comment]
Transitive npm deps from the `tsconfig` attribute in `ts_project` should _not_ get forwarded to downstream consumers via the JsInfo it provides or via runfiles.

**Comment by Toxaris** [comment]
I put together a repro in https://github.com/Toxaris/ts_config_deps_repro.

**Comment by Toxaris** [comment]
We figured out in Slack that disabling workers is a work-around. I updated the https://github.com/Toxaris/ts_config_deps_repro to also demonstrate the work around.

**Comment by gregmagolan** [comment]
Gotcha. That is quite possible as there seem to be a few more gremlins in worker mode.
cc @thesayyn

**Comment by gregmagolan** [comment]
@Toxaris The latest release of rules_ts has a big refactor for worker mode. When you have a chance could you please try turning working mode back on in your repro?

**Comment by gregmagolan** [comment]
Fix will be included in v1.13.0 which I'm going to cut right after https://github.com/aspect-build/rules_ts/pull/316 lands
