### ISSUE TITLE
[FR]: Add support for directory in srcs for ts_project

### ISSUE THREAD

**Issue by paulfariello** [aspect-build/rules_ts#282]
### What is the current behavior?

When generating files with a extrenal bazel rules (openapi for exemple), bazel doesn't have the list of srcs and instead only have a directory.

Currently ts_project doesn't support having a directory in ``srcs``.

defs.bzl

```
def _impl(ctx):
    output_dir = ctx.actions.declare_directory("my_outputs")
    command = "elided"

    ctx.actions.run_shell(
        command = command,
        outputs = [output_dir]
    )
    return [DefaultInfo(files = depset([output_dir])),]

my_rule = rule(
    implementation = _impl,
)
```

BUILD.bazel
```
load(":defs.bzl", "my_rule")

my_rule(
  name = "my_target",
)

ts_project(
  name = "project",
  srcs = [":my_target"],
)
```

Outputs:

```
Error in fail: ts_project target //project is configured to produce no outputs.

This might be because
- you configured it with `noEmit`
- the `srcs` are empty
- `srcs` has elements producing non-ts outputs
```

### Describe the feature

Allowing for dynamic file list in ts_project.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by dvins** [comment]
@paulfariello Do you know (or does anyone else know) of a work around for this? We're generating code in a previous rule step and it has multiple outputs in a directory as per example above, but the generated typescript files never get picked up in the ts_project rule.

**Comment by thesayyn** [comment]
this is due to the pre-declaration of output files by ts_project. it has to be able to enumerate files in the loading phase where treeartifacts can't be expanded, hence the issue.

**Comment by dvins** [comment]
@thesayyn Is this a solvable issue in the ts_project ruleset that is just yet to be implemented?

**Comment by thesayyn** [comment]
> @thesayyn Is this a solvable issue in the ts_project ruleset that is just yet to be implemented?

it can be implemented but we'd have to give up on predeclared outputs. question is do we want to flatten the treeartifact or just expand the treeartifact and put the outputs in their respective directories under outdir which would be basename of the directory.

**Comment by dvins** [comment]
> > @thesayyn Is this a solvable issue in the ts_project ruleset that is just yet to be implemented?
> 
> it can be implemented but we'd have to give up on predeclared outputs. question is do we want to flatten the treeartifact or just expand the treeartifact and put the outputs in their respective directories under outdir which would be basename of the directory.

Me *thinks* the latter? The issue in our case is with artifact generation that via `ts_project` rule _srcs_ either has to make it into the TypeScript compilation process (generated code) and/or _data_ into the distribution (generated JSON schemas) and ultimately into the package we build via the `npm_package` rule.

**Comment by dvins** [comment]
Any chance directory support may get some attention soon? The single file constraint is a big inhibitor when it comes to code generation output.

**Comment by alexeagle** [comment]
This is covered here:

https://github.com/aspect-build/rules_ts/blob/main/docs/troubleshooting.md#troubleshooting-ts_project-failures

>ts_project needs to know which .ts sources exist. If you have a tool which produces an "opaque" folder of .ts files and you cannot predict what they will be, then you can use tsc directly.
