### ISSUE TITLE
1.20.0 release notes has inaccurate usage example

### ISSUE THREAD

**Issue by ztl8702** [aspect-build/rules_ts#296]
according to https://github.com/aspect-build/rules_ts/blob/ad69d9358f47fba10ae46b3e9d4661ec14aef5a3/e2e/bzlmod/MODULE.bazel, `npm_google_protobuf` and `npm_at_bazel_worker` are no longer needed.

yet: 

https://github.com/aspect-build/rules_ts/releases/tag/v1.2.0

<img width="649" alt="Screenshot 2023-01-29 at 10 06 55 pm" src="https://user-images.githubusercontent.com/2714446/215322056-6d00eda9-3c27-46a9-9ef0-a38889108892.png">

^ this could result in:

```
ERROR: Analysis of target '<some target>' failed; build aborted: module extension "ext" from "@aspect_rules_ts~1.2.0//ts:extensions.bzl" does not generate repository "npm_google_protobuf", yet it is imported as "npm_google_protobuf" in the usage at <root>/MODULE.bazel:50:29
```

**Comment by gregmagolan** [comment]
Thanks for catching that. Those two lines are no longer needed as of 1.12.0. I updated the releases notes there and release notes generator is fixed up here: https://github.com/aspect-build/rules_ts/pull/297
