### ISSUE TITLE
[Bug]: [Worker] two composite projects in the same package leads to missing .tsbuildinfo output

### ISSUE THREAD

**Issue by purkhusid** [aspect-build/rules_ts#309]
### What happened?

There seems to be some non-determinism regarding the tsbuildinfo file when using the worker.
I get the following error when I build the targets:
```
/home/danielp/dannidev/repos/purkhusid/rules_ts_worker_repro/src/nodejs/nextjs_bootstrap/src/nextjs_bootstrap/pages/BUILD.bazel:21:11: output 'src/nodejs/nextjs_bootstrap/src/nextjs_bootstrap/pages/specs.tsbuildinfo' was not created
```

### Version

Development (host) and target OS/architectures:
Fedora Linux 37

Output of `bazel --version`:
```
Bazelisk version: development
Build label: 6.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 15:52:35 2022 (1671465155)
Build timestamp: 1671465155
Build timestamp as int: 1671465155
```

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
rules_js: 1.18.0
rules_ts: 1.2.4

Language(s) and/or frameworks involved:
Typescript

### How to reproduce

```shell
Reproduction here: https://github.com/purkhusid/rules_ts_worker_repro

You can checkout the repo and run `bazel build //...` and then `bazel clean` and then `bazel build //...` again.

The issue seems to stem from two `ts_project` targets being in the same folder but I have not confirmed that it is the case.
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by thesayyn** [comment]
thank you for the reproduction. I'll work on a fix.

**Comment by purkhusid** [comment]
@thesayyn I'm thinking of attempting to fix this issue but could use some directions when it comes to debugging this. Do you have any useful pointers on where to start if my gut tells me that this is because there are 2 ts_project targets in the same package?

**Comment by thesayyn** [comment]
That's right. to confirm you could try passing two different tsconfig two those two targets. by default ts_project worker will spawn one tsc per package, so your two ts_project targets is sharing the same tsc and tsc behaves wrong in this case.

**Comment by alexeagle** [comment]
We are moving away from supporting the Persistent Worker mode in the next major release, 2.0.0. So I don't think we'll ever fix this, sorry!
