### ISSUE TITLE
[FR]: New example for unit testing

### ISSUE THREAD

**Issue by jimmyt857** [aspect-build/rules_ts#325]
### What is the current behavior?

Currently there is [a single example](https://github.com/aspect-build/rules_ts/tree/main/examples/js_test) involving unit tests.

### Describe the feature

As someone familiar with Bazel in general but new to typescript and particularly unit testing in typescript, I am having trouble extrapolating how to set up my project. A slightly more involved example would be incredibly helpful here, possibly including:

 - More than 1 test in the test file
 - At least 1 other `.ts` file in the directory, which the test must import and depend on
 - A `main.ts` somewhere, which includes the same library as the test, but does not include the test code in the compiled result.
 - Bonus: Possibly a separate example, utilizing `rules_jest` with typescript and bazel.

I was banging my head against this for a few hours this weekend and couldn't quite get it, but I intend to try again in the next week and will make my own PR for this if I am able to figure it out. Any help or even just a nudge on roughly how this should be set up would be greatly appreciated though!

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by jimmyt857** [comment]
I stumbled across [this example](https://github.com/aspect-build/bazel-examples/tree/main/jest) which covers most of my issues. It looks like this is also maintained by the Aspect team, so it seems like the only remaining issue here is perhaps to make some of these examples more discoverable.

Going to leave this bug open just to make sure someone eventually sees this, but otherwise it can be considered resolved.

**Comment by gregmagolan** [comment]
Yes, we generally add more complex examples to the bazel-examples repository to not excessively bloat the rules repositories. The release archives are just a tarball of the entire repo so its good to keep them trim. Will tag this as "documentation" as a reminder to add something to the main README here to point to bazel-examples.
