### ISSUE TITLE
[Bug]: ts_project in external repository declares tsbuildinfo output path incorrectly

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/rules_ts#329]
### What happened?

https://bazelbuild.slack.com/archives/CULGHFKCK/p1677603586848049

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gzm0** [comment]
Following up from slack: 

I managed to locally fix it like this:

```diff
@@ -160,7 +160,7 @@ See https://github.com/aspect-build/rules_ts/issues/228 for more details.
     if ctx.outputs.buildinfo_out:
         arguments.add_all([
             "--tsBuildInfoFile",
-            ctx.outputs.buildinfo_out.short_path,
+            to_output_relative_path(ctx.outputs.buildinfo_out),
         ])
         outputs.append(ctx.outputs.buildinfo_out)
     output_sources = json_outs + js_outs + map_outs + copy_files_to_bin_actions(ctx, ctx.files.assets)
```

**Comment by gzm0** [comment]
Workaround I could find so far (`tsconfig.json` also needs adjustment of course):

```diff
 ts_project(
   ...
-  composite = True
+  composite = False
+  incremental = False
+  declaration = True
)
```
