### ISSUE TITLE
[FR]: Add example/support for typescript code-generation target dependencies

### ISSUE THREAD

**Issue by RobertDiebels** [aspect-build/rules_ts#340]
### What is the current behavior?

ts_project does not provide a mechanism to define dependencies on targets that generate typescript-files.

All three common Bazel attributes (srcs, data, deps) for defining dependencies do not seem to support targets that output ts-files.

### Describe the feature

I have a typescript project which depends on npm-package `cdk8s-cli` which is used to generate typescript files for Kubernetes resources. These files can then be used to create yaml files for Kuberenetes objects.

I have managed to generate the files in a manner that I expect. 
However, on the `ts_project` rule I cannot define a dependency on the `run_js_binary` target that generates the typescript files.
This causes the rules to fail. It is unclear to me how I can define a dependency on that target and I'm looking for an example or support in case this edge-case should be, but is not, supported.

**Comment by RobertDiebels** [comment]
> What error are you seeing when you try this?

Well, I am passing the target label to the run_js_binary rule instead of the files that it generates. Since the files themselves may not exist yet. Is this the correct approach? Or do I need to invoke each rule in order instead of assuming that Bazel will resolve the dependency on another rule? 

It may be (quite likely) that I do not understand Bazel and it's ecosystem well enough as I am a relatively new and attempting to understand its core tenants.

In any case, thank you for your reply!

**Comment by gregmagolan** [comment]
Yes, passing the `js_run_binary` target is correct. It will fail, however, if your `js_run_binary` is outputting a directory (tree artifact) instead of individual `.ts` files since an opaque directory cannot be used as an input to `ts_project`.

What does your `js_run_binary` look like?

**Comment by RobertDiebels** [comment]
@gregmagolan Hi Greg. The relevant BUILD.bazel file looks like this:

```
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_test")
load("@aspect_rules_js//js:defs.bzl", "js_run_binary")

npm_link_all_packages(name = "node_modules")

###########################
# import cdk8s constructs #
###########################
directory_path(
    name = "cdk8s_entrypoint",
    directory = ":node_modules/cdk8s-cli/dir",
    path = "lib/cli/index.js",
    visibility = ["//visibility:public"],
)

js_binary(
    name = "cdk8s",
    data = [":node_modules/cdk8s-cli"],
    entry_point = ":cdk8s_entrypoint",
    visibility = ["//visibility:public"],
    chdir = package_name(),
)

js_run_binary(
    name = "cdk8s_import",
    srcs = ["cdk8s.yaml"],
    outs = ["imports/acme.cert-manager.io.ts", "imports/cert-manager.io.ts", "imports/k8s.ts"],
    args = ["import"],
    log_level = "debug",
    tool = ":cdk8s",
    visibility = ["//visibility:public"],
)

#################
# build project #
#################

load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "ts",
    declaration = True,
    resolve_json_module = True,
    srcs = [":cdk8s_import"],
)
```

The `cdk8s.yaml` contains some definitions which will result in the files being written to an "imports".
I tried using the `out_dirs` attribute with value `["imports"]` with the `outs` attribute elements no longer referencing the `imports`-folder.  For some reason that caused the rule to fail so I remove the "out_dirs" attribute.

**Comment by gregmagolan** [comment]
Using `out_dirs` would fail since ts_project can't accept directories in `srcs`. Does switching to `outs` resolve it for you?

**Comment by RobertDiebels** [comment]
I'm sorry, I meant using `out_dirs` in the `js_run_binary` rule. Switching to `outs` resolved the issue there.
However using `srcs = [":cdk8s_import"],` in `ts_project` does not work, even-though I absolutely have to run that target before running the `ts_project` rule.

**Comment by gregmagolan** [comment]
I think you have to be more specific on what error you're seeing. Log outputs are helpful to see. A minimal repro is usually the best way to get help if you're  hitting something unusual.
