### ISSUE TITLE
[Bug]: ts_project in npm_package(deps) causes tsc to run in addition to transpiler

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_ts#352]
### What happened?

When switching to swc or another transpiler any performance advantages are ruined if `ts_project` targets go through an `npm_package` which forces declarations to be built.

### How to reproduce

```shell
esbuild(
   entry = "main.js"
   deps = [":pkg"],
)

npm_package(
  name = "pkg",
  srcs = [":a-ts_project"]
)
```

**Comment by alexeagle** [comment]
After https://github.com/aspect-build/rules_js/pull/1205 lands, we just need to improve the docs here to help developers discover this option.

**Comment by alexeagle** [comment]
Documentation for this added in #404
