### ISSUE TITLE
[Bug]: `tsc` passes outside of Bazel but fails with `rules_ts`

### ISSUE THREAD

**Issue by UebelAndre** [aspect-build/rules_ts#356]
### What happened?

I have a repro here: https://github.com/UebelAndre/rules_ts_example

The README describes a case where running `tsc` on some code outside of bazel succeeds but fails when using `rules_ts`. 

```
~/Code/rules_ts_example (main ✗) bazel build //...
INFO: Analyzed 3 targets (1 packages loaded, 50 targets configured).
INFO: Found 3 targets...
ERROR: /Users/user/Code/rules_ts_example/foo/BUILD.bazel:11:11: Compiling TypeScript project @//foo:foo_ts [tsc -p foo/tsconfig.json] failed: (Exit 1): tsc.sh failed: error executing command (from target //foo:foo_ts)
  (cd /private/var/tmp/_bazel_user/729471d7b159995c3ffbf36ad2691a5e/sandbox/darwin-sandbox/300/execroot/rules_ts_example && \
  exec env - \
    BAZEL_BINDIR=bazel-out/darwin_arm64-fastbuild/bin \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc.sh --project foo/tsconfig.json --outDir foo --rootDir foo --declarationDir foo --tsBuildInfoFile foo/foo_ts.tsbuildinfo)
# Configuration: 0ba77a61754b8ccac68b4c11211b3ebeca24c2f07acb9bc57df3ce73dcecadb5
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
foo/src/index.tsx(40,10): error TS2786: 'Head' cannot be used as a JSX component.
  Its instance type 'Head' is not a valid JSX element.
    Type 'Head' is missing the following properties from type 'ElementClass': setState, forceUpdate, props, state, refs
foo/src/index.tsx(50,18): error TS2339: Property 'props' does not exist on type 'MyDocument'.
foo/src/index.tsx(55,12): error TS2786: 'NextScript' cannot be used as a JSX component.
  Its instance type 'NextScript' is not a valid JSX element.
    Type 'NextScript' is missing the following properties from type 'ElementClass': setState, forceUpdate, props, state, refs
INFO: Elapsed time: 3.645s, Critical Path: 3.19s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 6.1.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
rules_js-1.24.1
rules_ts-1.3.2

Language(s) and/or frameworks involved:

### How to reproduce

```shell
See https://github.com/UebelAndre/rules_jest_example
```

**Comment by jbedard** [comment]
This seems very similar to https://github.com/vercel/next.js/discussions/17205#discussioncomment-4927294 and https://github.com/vercel/next.js/issues/40835? Do any of the suggestions there work?

**Comment by jbedard** [comment]
Actually this is the same issue as https://github.com/aspect-build/rules_ts/issues/344 and with strict dependencies will occur outside bazel as well.

`next` (and maybe `@next/font`?) both declare `@types/react` as a dev-dependency so it's  ignored by pnpm and rules_js from your project. With strict deps in rules_js or with pnpm `hoist=false` `@types/react` will not be accessible to `next` when typescript is type-checking. Your `MyDocument` extends the next `Document` which extends `React.Component`, but since `next` doesn't depend on `@types/react` that `React.Component` is essentially undefined. So your `MyDocument` is not a react component from typescripts perspect with strict dependencies...

You should be able to workaround this by correcting the dependency via [hoisting](https://docs.aspect.build/rules/aspect_rules_js/docs/pnpm/#hoisting) or pnpm [package extensions](https://pnpm.io/package_json#pnpmpackageextensions).

**Comment by UebelAndre** [comment]
@jbedard sorry but could you suggest a diff to https://github.com/UebelAndre/rules_ts_example that would fix the issue? I've tried using package extensions and it felt like shooting in the dark 😞

**Comment by jbedard** [comment]
Do the docs changes in https://github.com/aspect-build/rules_ts/pull/359 help at all? Have any suggestions? I'll also try getting a quick diff that you can checkout...

**Comment by jbedard** [comment]
This in your package.json seems to do it:
```
diff --git a/package.json b/package.json
index bc89f32..3441cfe 100644
--- a/package.json
+++ b/package.json
@@ -9,5 +9,14 @@
   "version": "1.0.0",
   "devDependencies": {
     "typescript": "4.9.4"
+  },
+  "pnpm": {
+    "packageExtensions": {
+      "next": {
+        "dependencies": {
+          "@types/react": "*"
+        }
+      }
+    }
   }
 }
```

This way the strict (no hoisting) `node_modules` makes `@types/react` accessible to `next` which imports+exposes react (while only declaring it as a dev-dependency which does nothing when consuming `next`).

**Comment by UebelAndre** [comment]
> Do the docs changes in #359 help at all? Have any suggestions? I'll also try getting a quick diff that you can checkout...

Why suggest `skipLibCheck`? Does that weaken the validation of my code? Or is typescript running on transitive dependencies?

**Comment by UebelAndre** [comment]
> Actually this is the same issue as #344 and with strict dependencies will occur outside bazel as well.
> 
> `next` (and maybe `@next/font`?) both declare `@types/react` as a dev-dependency so it's ignored by pnpm and rules_js from your project. With strict deps in rules_js or with pnpm `hoist=false` `@types/react` will not be accessible to `next` when typescript is type-checking. Your `MyDocument` extends the next `Document` which extends `React.Component`, but since `next` doesn't depend on `@types/react` that `React.Component` is essentially undefined. So your `MyDocument` is not a react component from typescripts perspect with strict dependencies...
> 
> You should be able to workaround this by correcting the dependency via [hoisting](https://docs.aspect.build/rules/aspect_rules_js/docs/pnpm/#hoisting) or pnpm [package extensions](https://pnpm.io/package_json#pnpmpackageextensions).

@jbedard sorry, reading this again and I don't understand why `@types/react` wouldn't be accessible to `next`. Doesn't having it as a `devDependency` in *my* package make `@types/react` globally accessible?

**Comment by jbedard** [comment]
> Doesn't having it as a devDependency in my package make @types/react globally accessible?

It makes it accessible to your code, not your dependencies. We don't want adding a local dependency to have side-effects on other packages without explicitly declaring it.

> Why suggest skipLibCheck? Does that weaken the validation of my code? Or is typescript running on transitive dependencies?

Both to avoid checking libraries with type issues like what you're seeing and performance, see https://www.typescriptlang.org/tsconfig#skipLibCheck
