### ISSUE TITLE
[Bug]: Cannot use `select` with `source_map` of `ts_project`

### ISSUE THREAD

**Issue by arobinson** [aspect-build/rules_ts#366]
### What happened?

`ts_project` macro fails to build when the `source_map` attribute is given a `select` value to conditionally enable source maps

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
bazel 6.2.0

### How to reproduce

1. Clone https://github.com/arobinson/rules_ts_source_map_issue:
```shell
git@github.com:arobinson/rules_ts_source_map_issue.git
```
2. Run a build:
```shell
pnpm i && pnpm run build
```

### Any other information?

Error:
```
ERROR: ...rules_ts_source_map_issue/BUILD.bazel:24:11: in ts_project_rule rule //:compile: 
...external/aspect_rules_ts/ts/private/ts_project.bzl:34:5: The following files have no generating action:
src/a.js.map
ERROR: ...rules_ts_source_map_issue/BUILD.bazel:24:11: Analysis of target '//:compile' failed
ERROR: Analysis of target '//:compile' failed; build aborted: 
INFO: Elapsed time: 0.140s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 47 targets configured)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jbedard** [comment]
`select` statements are only evaluated once the rule is executed and not within a macro. We need to know the `source_map` value when the macro runs in order to pre-declare the outputs of the rule.

Is it essential to not generate them? I'd think re-running tsc when that flag switches would slow things down a lot.

Thanks for creating the repo to test it out, that makes it a lot easier 👍

**Comment by arobinson** [comment]
yes, in our production build it is vital that source maps are not used as we need a highly performant build. Only for client debugging do we want to optionally turn them on. I have them turned off on certain files and I was trying to be nice to provide a way to make them optional

**Comment by jbedard** [comment]
You'll have to use the underlying rule instead of the macro then. The macro mainly just adds a convenient API over the rule to do things like pre-declaring outputs, supporting tsconfig as a `dict()` etc.

See https://docs.aspect.build/rules/aspect_rules_ts/docs/rules/#ts_project_rule

**Comment by arobinson** [comment]
I moved onto other tasks, so couldn't spend time on the alternative. Given that this is a macro, it makes sense. I didn't realize at the time it wasn't a real rule. So yes, I think it can be closed.

**Comment by jbedard** [comment]
I'm going to close this then, let us know if you run into further issues if you spend more time on this.
