### ISSUE TITLE
[FR]: Allow ts to be downloaded through other URLs

### ISSUE THREAD

**Issue by hjellek** [aspect-build/rules_ts#380]
### What is the current behavior?

When invoking `rules_ts_dependencies`, Typescript is downloaded from registry.npmjs.org (https://github.com/aspect-build/rules_ts/blob/main/ts/private/npm_repositories.bzl#L87) and there is no way to override this.

### Describe the feature

It would be nice to be able to supply another URL where typescript can be downloaded from (like bazelisk https://github.com/bazelbuild/bazelisk#where-does-bazelisk-get-bazel-from for example).

It would be possible to for example add an optional urls parameter to `npm_dependencies`.

In our company we proxy all external repositories through proxies to be able to revoke packages, and to get speed improvements by having a cache near our site.

**Comment by mattem** [comment]
As this is using Bazel's downloader, you could achieve this by setting [--experimental_downloader_config](https://bazel.build/reference/command-line-reference#flag--experimental_downloader_config) and a rewrite rule specified in the configuration file.

**Comment by hjellek** [comment]
> As this is using Bazel's downloader, you could achieve this by setting [--experimental_downloader_config](https://bazel.build/reference/command-line-reference#flag--experimental_downloader_config) and a rewrite rule specified in the configuration file.
> 
> It's a little hidden, but it's subtly documented under `npm_import`, but the process is the same here. https://docs.aspect.build/rules/aspect_rules_js/docs/npm_import#npm_import

@mattem 
Thanks, that's definitely a good thing to know about!
It has totally escaped my attention previously. 

Closing the issue.
