### ISSUE TITLE
[Bug]: ts_project incorrectly propagates testonly to build_test

### ISSUE THREAD

**Issue by sallustfire** [aspect-build/rules_ts#468]
### What happened?

ts_project with a custom transpiler uses build_test to get a test target to enforce type-checking. It receives common_kwargs, but unlike the other rules used by that macro it's a rule with implementation test = True. So, it breaks during analysis if an inconsistent testonly value is passed through e.g. testonly = False. build_test can only take None or True.

### Version

Development (host) and target OS/architectures: Pop!_OS 22.04 x86_64

Output of `bazel --version`: 6.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: main (8cdcab7)

Language(s) and/or frameworks involved:

**Comment by jbedard** [comment]
Fixed in #469
