### ISSUE TITLE
[Bug]: ts_project macro creates an unused validate_options target if validate is True

### ISSUE THREAD

**Issue by PeterD1524** [aspect-build/rules_ts#517]
### What happened?

foo/BUILD.bazel:
```bazel
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "foo",
    srcs = [
        "index.ts",
    ],
    validate = True,
)
```
The ts_project macro above creates two targets: //foo:foo (ts_project_rule) and //foo:_validate_foo_options (validate_options). Currently //foo:_validate_foo_options is not used by //foo:foo. I think //foo:foo should depend on //foo:_validate_foo_options.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 7.0.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: aspect_rules_ts 2.1.0

Language(s) and/or frameworks involved: TypeScript

### How to reproduce

Minimal repro: https://github.com/PeterD1524/cuddly-octo-giggle

Running
```shell
bazel query '...'
```
will show
```
//foo:_validate_foo_options
//foo:foo
```
Running
```shell
bazel build '//foo:foo'
```
will succeed.

Running
```shell
bazel build '//foo:_validate_foo_options'
```
will fail with the following error:
```
ERROR: ts_project rule //foo:foo was configured with attributes that don't match the tsconfig
 - attribute declaration=false does not match compilerOptions.declaration=true
```

I think `bazel build '//foo:foo'` should fail.

### Any other information?

related commit: https://github.com/aspect-build/rules_ts/commit/18a506393ef1fe988702863bbd30beb03ab835d2
validate_options creates a target with a validation action which checks the tsconfig.
suggestions how to fix:
ts_project_rule can accept a new attribute label which should be a validate_options target and the ts_project macro should send the validate_options target it created to ts_project_rule.

**Comment by alexeagle** [comment]
Hi @PeterD1524  thanks for filing this. We changed the way validation is wired in https://github.com/aspect-build/rules_ts/pull/138 but your repro shows that we've made some horrible mistake and are "failing open" by not running the validation at all.
