### ISSUE TITLE
[Bug]: Suggestion to add "query --@aspect_rules_ts//ts:skipLibCheck=always" to .bazelrc breaks queries

### ISSUE THREAD

**Issue by jamirvin** [aspect-build/rules_ts#524]
### What happened?

I followed the suggestion [here](https://github.com/aspect-build/rules_ts/blob/5d0c6227e5b96281f296e5cc5382d7d58b4a8bde/ts/BUILD.bazel#L40) to add "query --@aspect_rules_ts//ts:skipLibCheck=always" to my .bazelrc, but this breaks all bazel queries. 

Example:
`$ bazel query 'filter("test*", //src/...)'` 
 `ERROR: Error while parsing '--@aspect_rules_ts//ts:skipLibCheck=always filter("test*", //src/...)': syntax error at '- - @aspect_rules_ts//ts:skipLibCheck'`

Removing this from my .bazelrc file resolves the issue, and it's unclear if it's having any negative effect. Is this only supported in a later version of Bazel?

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
WARNING: info command does not support starlark options. Ignoring options: [--@aspect_rules_ts//ts:skipLibCheck=always]
Build label: 5.4.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 15 16:14:44 2022 (1671120884)
Build timestamp: 1671120884
Build timestamp as int: 1671120884

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
rules_ts version: 2.1.0

**Comment by alexeagle** [comment]
Yes, it's easy to confirm in the `e2e/workspace` folder here:

```
alexeagle@MacBook-Pro-8 workspace % USE_BAZEL_VERSION=6.0.0 bazel query ...
Starting local Bazel server and connecting to it...
//:_validate_ts_options
//:test
//:test_0__deps
//:ts
Loading: 1 packages loaded

alexeagle@MacBook-Pro-8 workspace % USE_BAZEL_VERSION=5.4.1 bazel query ...
2024/01/25 21:02:07 Downloading https://releases.bazel.build/5.4.1/release/bazel-5.4.1-darwin-arm64...
Starting local Bazel server and connecting to it...
ERROR: Error while parsing '--@aspect_rules_ts//ts:skipLibCheck=honor_tsconfig --@aspect_rules_ts//ts:default_to_tsc_transpiler ...': syntax error at '- - @aspect_rules_ts//ts:skipLibCheck'
Loading: 0 packages loaded
```

After removing the `query` lines from bazelrc, I checked that alternating between `bazel test` and `bazel query` doesn't cause the analysis cache to be discarded, which is the main performance problem I was concerned about, so I think it's fine to remove.
