### ISSUE TITLE
[FR]: Multiply proto files in BUILD directory with copy_files options

### ISSUE THREAD

**Issue by SinimaWath** [aspect-build/rules_ts#548]
### What is the current behavior?

If you have more then one proto in directory:

```
proto
    one.proto
    second.proto
    BUILD.bazel
```

And will try to use ts_proto_library rule:
```bazel
load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "one_proto",
    srcs = ["one.proto"],
)

proto_library(
    name = "second_proto",
    srcs = ["second.proto"],
)


ts_proto_library(
    name = "one_ts_proto",
    node_modules = "//:node_modules",
    proto = ":one_proto",
)

ts_proto_library(
    name = "second_ts_proto",
    node_modules = "//:node_modules",
    proto = ":second_proto",
)
```

You will get error:

Error in directory_path: directory_path rule '_one_pb.d.ts_dirpath' in package 'proto' conflicts with existing directory_path rule, defined at proto/BUILD.bazel:18:17

### Describe the feature

Somehow `ts_proto_library` needs works with multiply files and able to copy generated files

**Comment by alexeagle** [comment]
Thanks, this is mitigated by https://github.com/aspect-build/rules_ts/pull/617 (which forces you to be more explicit than we'd like, but does illustrate two ts_proto_library in one package)
