### ISSUE TITLE
[Bug]: .ts source file labels produce invalid predeclared outputs unless they are bare

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_ts#584]
### What happened?

If labels such as
`srcs = ["@//path/to:a.ts", "//path/to:b.ts", ":c.ts", "d.ts"]`
 are specified in `ts_project(srcs)` then the pre-declared outputs are invalid, and fail with an error like

```
invalid label 'generated/:a.js' in element 0 of attribute 'js_outs' in 'ts_project' rule: invalid package name 'generated/': package names may not end with '/'
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
write_file(
    name = "gen-a.ts",
    out = "a.ts",
    content = [
        "export const a = 42",
    ],
)


ts_project(
    name = "target-refs",
    srcs = [
        ":gen-a.ts",
    ],
    declaration = True,
    out_dir = "target-refs",
    source_map = True,
)

ts_project(
    name = "out-target-refs",
    srcs = [
        ":a.ts",
        ":b.ts",
    ],
    declaration = True,
    out_dir = "out-target-refs",
    source_map = True,
)
```

**Comment by alexeagle** [comment]
The correct answer here has to be to preserve what users understand as Label semantics, which is that 

`path/to/BUILD.bazel`:
```
srcs = ["@//path/to:a.ts", "//path/to:b.ts", ":c.ts", "d.ts"]
# is the same as
srcs = ["a.ts", "b.ts", "c.ts", "d.ts"]
```

So we should simply normalize the syntax before computing the out_path.
