### ISSUE TITLE
Examples do not contain WORKSPACE files

### ISSUE THREAD

**Issue by gonzojive** [aspect-build/rules_ts#64]
Lack of workspace files makes it difficult to copy the example directories and have them compile as is.

**Comment by alexeagle** [comment]
I'm still not convinced this is better for users, and I'm quite sure it makes it harder for us as maintainers. Deferring to after 1.0

**Comment by gonzojive** [comment]
One data point: My experience with examples in bazel repos is having a copy-paste-able `WORKSPACE` file makes it easier to get up and running. Otherwise it's necessary to have a fair amount of bazel knowledge to write the WORKSPACE file by hand. I have given up a few times trying to get rules_nodejs examples to work in the past because the WORKSPACE files were written for the rule developers & didn't work when copy pasted into a fresh git repo.

I can certainly see it being more work for maintainers.

**Comment by alexeagle** [comment]
We now include a fully functioning WORKSPACE snippet on every release notes and point there for "how to install", do you think that's sufficient?

**Comment by gonzojive** [comment]
It's not quite as user friendly because the casual user must know where to look to hunt down the right WORKSPACE snippet. I would also expect some examples to depend on libraries other than rules_ts, so the user would need to hunt those down.

I'm not sure what the easy-to-maintain solution is, but as a user I just want all of the files within an example directory to be able to be copied into a fresh git repo and built with `bazel build //... && bazel test //...`.

**Comment by alexeagle** [comment]
I see, that's how it works in our https://github.com/aspect-build/bazel-examples repo.

I don't imagine individual test cases of ts_project being useful as a seed to start a new project, they're very small scope and you wouldn't get enough WORKSPACE content to expand from there to make something useful.

**Comment by gregmagolan** [comment]
bzlmod with Bazel 6 should should make it much easier for users to get up and running. rules_js & rules_ts now both support bzlmod.

**Comment by alexeagle** [comment]
I can't imagine we'll ever find time to dig into whether we want to make a change, and then actually make it across all our rules repos.
