### ISSUE TITLE
Custom transpiler + ESM + type checking fails due to require in ts_project_worker.js

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_ts#68]
Hey,

For various reasons I am looking at ESM builds with `rules_ts`, where the outputs then need to be run in node. Here's how I've got things set up.

Firstly, the `package.json` file in the root.

```json
{
  "name": "repro",
  "version": "1.0.0",
  "type": "module"
}
```

The `"type": "module"` means that I can use `import` and `export` statements from `.js` files in bin, assuming I copy the `package.json` file over to bin with `copy_to_bin` (which is what I'm currently doing).

Then I have the following in `//src`:

```
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@aspect_rules_swc//swc:defs.bzl", "swc_transpiler")
load("@bazel_skylib//lib:partial.bzl", "partial")

ts_project(
    name = "src",
    srcs = [
        "index.ts",
    ],
    declaration = True,
    source_map = True,
    transpiler = partial.make(
        swc_transpiler,
        source_maps = "true",
    ),
    tsconfig = "//:tsconfig",
)
```

So I can run `bazel build //src` and `bazel build //src:src_typecheck` (which is a feature I love btw).

And for `//:tsconfig` in the root I have:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "sourceMap": true,
    "declaration": true
  }
}
```

Finally, to trigger the issue it's a case of:

1. `bazel clean`
2. `bazel build //:copy_package`
3. `bazel build //src:src_typecheck`

What seems to happen is that ultimately we land in `bin/external/npm_typescript/ts_project_worker.js`, and it resolves the copied `package.json`, which is telling node to run with ESM support. However, within `ts_project_worker.js` there are `require` statements, which it no longer likes. (I've cleaned up some of the paths to try and aid clarity here.)

```sh
Compiling TypeScript project //src:src_typings [tsc -p tsconfig.json] failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at bazel-workers/worker-9-TsProject.log ---8<---8<---
bin/external/npm_typescript/ts_project_worker.js:1
const fs = require('fs');
           ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'execroot/__main__/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at bin/external/npm_typescript/ts_project_worker.js:1:12
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
---8<---8<--- End of log ---8<---8<---
Target //src:src_typecheck failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

I hope all of that makes sense.

Only thoughts I've had:

1. Can `ts_project_worker.js` be renamed to `ts_project_worker.cjs` so that it works for both CJS and ESM?
2. Is there a way to prevent the node process running `ts_project_worker.js` from resolving the root-level `package.json` in `bin`? It's needed to run another binary, it just happens to be in the `bin` dir when the `_typecheck` rule is run.

**Comment by paullewis** [comment]
Hi, yes I've created a repo here with a repro: https://github.com/paullewis/repro-rules-ts-issue-68

The `README.md` has the info about how to reproduce the issue, but it mostly seems a case that the default node import behavior is changed by the presence of `"type": "module"` in `bin/package.json`, and that then breaks when node runs `ts_project_worker.js` since it no longer expects CJS.

**Comment by thesayyn** [comment]
Cool. I'll take a look today.

**Comment by thesayyn** [comment]
update: the second issue seems to be the problem with rules_js instead of rules_ts. what happens is that nodejs binary sees the package.json and takes it into consideration when deciding whether to use ESM or CJS.

**Comment by paullewis** [comment]
Yeah that makes sense. It's running node in ESM mode, but the `ts_project_worker.js` file that's running is still CJS and it gets upset, right?

**Comment by thesayyn** [comment]
Right. Also, I have concerns about `cjs` extension. I don't know which versions of the node support this extension. the behavior of nodejs is really non-hermetic in this case.  

the only workaround that I see is; turning the `--worker_sandboxing` flag on. this might have some cache implications though since the worker is not capable of handling the file path changes.

**Comment by thesayyn** [comment]
I can't think of a solution that is backward compatible and seems like there is no way to stop nodejs from reading the package.json file.

**Comment by paullewis** [comment]
Yes, I can see that concern, and I agree that the lack of hermeticity is concerning here. As far as I can tell the `cjs`/`mjs` file extension was introduced around v16 (the current LTS release), but I'm not certain. In any case, as you say, anyone who uses ESM and ends up with the `package.json` in `bin` will hit this because Node will go looking for it.

**Comment by paullewis** [comment]
I mean, this isn't generally going to go away inasmuch as Node seems to support both `require` and `import`/`export`, just not at the same time. There doesn't seem to be any CLI flag to toggle the mode, which would have been nice (as it could have been tagged onto `js_binary` or what have you). Instead they seem to pick it up either from the file suffixes or the `package.json`.

**Comment by thesayyn** [comment]
they have `--input-mode` which seems to only work with `--eval` and STDIN. there is a discussion about introducing `--package-type` flag but seems like nodejs contributors are not warm to the idea.  Nevertheless, I believe the better solution here is to flip `--worker_sandboxing` on by default and make worker support that flag.

**Comment by paullewis** [comment]
Yeah I had wondered whether it would be possible to offer a transpilation option to get files over to `mjs`, but here again we hit issues because the TS Compiler only outputs `js` and SWC has an open bug for it, but nothing landed as yet.

Out of interest, what does the `--worker_sandboxing` flag do, and how does that help? (Just trying to learn a bit.)

**Comment by paullewis** [comment]
Ah I see. In this particular instance, though, if I wanted to run `src.js` as ESM, I could present the `package.json` as well (via a `dep` I guess?) with the type property set, and we'd still have the same challenge. Would the fix be to offer an `mjs` variant of `ts_project_worker`, or am I missing the point?

**Comment by paullewis** [comment]
Oh, so does this mean that `ts_project_worker.js` runs under commonjs, but then other stuff can run as ESM?

**Comment by thesayyn** [comment]
Exactly without the cjs prefix.
