### ISSUE TITLE
_typecheck rule doesn't seem to run tsc

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_ts#79]
Hey, I've [created a repro repo for this](https://github.com/paullewis/repro-rules-ts-issue-79) (which I hope is helpful), but in essence I have the following Bazel file:

```bazel
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@aspect_rules_swc//swc:defs.bzl", "swc_transpiler")
load("@bazel_skylib//lib:partial.bzl", "partial")

ts_project(
    name = "src",
    srcs = [
        "src.ts",
    ],
    transpiler = partial.make(
        swc_transpiler,
    ),
    tsconfig = "//:tsconfig",
)
```

The contents of `src.ts` is minimal, but crucially it requires some types info from `@types/long`:

```typescript
import * as Long from 'long';
console.log(Long);

export const foo = 1;
```

From the docs I understand that `bazel build //src` would run swc and therefore no type checking will be done, and that I can then run `bazel build //src:src_typecheck` to invoke `tsc` separately - love that feature! However, when I do that it doesn't throw, despite the fact that `//:node_modules/@types/long` isn't set as a dependency.

If I then remove the custom transpiler so that `ts_project` always uses `tsc` then it throws the expected error:

```
src/src.ts(1,23): error TS2307: Cannot find module 'long' or its corresponding type declarations.
```

If I then add the types as a dependency of the non-swc build, it will build:

```bazel
ts_project(
    name = "src",
    srcs = [
        "src.ts",
    ],
    tsconfig = "//:tsconfig",
    deps = [
        "//:node_modules/@types/long"
    ]
)
```

So from that it looks like the `_typecheck` rule doesn't run `tsc`?

**Comment by paullewis** [comment]
Update: looks to be because I don't have `declaration = True` in the attributes / root `tsconfig.json`. Wondering if it should either toggle it on for the `_typecheck` case or throw if it's set to `False`?

**Comment by alexeagle** [comment]
Yeah I would have expected an error if tsc was being run for no outputs, which is the case for transpiler-only and no declarations

**Comment by paullewis** [comment]
Sort-of related other thing (just because I'm looking at this atm).

If I do a `tsc` build with the type `deps` in place with the above repo, _then_ comment them out, the second build still works (I guess because the types are still available somehow?). If I `bazel clean` and try again it fails saying it can't find the types for `long`.

**Comment by alexeagle** [comment]
I think that's a separate issue and is probably a bug in the worker mode, could you file another for that?

For this issue, this is the code I'd expect to have prevented the bug:
https://github.com/aspect-build/rules_ts/blob/main/ts/private/ts_project.bzl#L129-L132
do you have a couple minutes to debug and see why you didn't get into that conditional?

**Comment by paullewis** [comment]
Yes very happy to try and debug, but timezones being as they are I'm afk now. Will give it a whirl on Monday! ... And I'll file a bug for the other issue.

**Comment by paullewis** [comment]
Okay, so a few things. Let's see.

The reason the clause you highlighted doesn't execute is because there is a dep: `[<target //src:_validate_src_options>]`, which means the final condition of the `if` isn't satisfied. (For clarity, `js_outs` and `typings_outputs` are both empty, so they are both satisfy their conditions.)

The [line below that checks for `len(outputs)`](https://github.com/aspect-build/rules_ts/blob/main/ts/private/ts_project.bzl#L155) doesn't run the TS compiler, however, because `outputs` is empty. Even with `declaration` set to `true` in `tsconfig.json` I see the same values for `js_outs`, `typings_outputs`, and `ctx.attr.deps` unless I _also_ set `declaration` to `True` in `ts_project`.

If I set `declaration` attribute to `True` in `ts_project` _and_ have it set to `true` in `tsconfig.json` then it will run `tsc` in both the custom-transpiler case (`bazel build //src:src_typecheck`) and the no-custom-transpiler case.

**Comment by alexeagle** [comment]
Thanks - I don't think that `and not ctx.attr.deps` belongs on that condition. I did some digging and it was introduced back here https://github.com/bazelbuild/rules_nodejs/commit/96d37b6eb88ed72d40654fec5f1a9055ba5ee5e7 without an explanation of why.
Looks like the fix is just to restore that line.
