### ISSUE TITLE
Successive runs with differing/missing types don't fail

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_ts#80]
Super hard to find a good summary for this one! Anyway, picking up from #79, let's see if I can summarize.

The repro is in this repo (a repro repo!): https://github.com/paullewis/repro-rules-ts-issue-79

Essentially if you have the following:
```bazel
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "src",
    srcs = [
        "src.ts",
    ],
    declaration = True,
    tsconfig = "//:tsconfig",
    deps = [
        "//:node_modules/@types/long",
    ],
)
```

And here we can assume that `src.ts` uses the types in the `deps`. It builds just fine.

However, if we comment out the deps, rather than failing the build it still succeeds. @alexeagle mentioned in #79 that might be something to do with the worker mode, in case that's of use.

**Comment by thesayyn** [comment]
this still happening with the worker mode disabled. Weird.

**Comment by thesayyn** [comment]
> I thought this was because everything is copied to the output tree, but nothing removes those copies once dependency is removed

When sandboxed, this is not true. For worker mode, this is true though. However, that's not a problem since ts_project_worker has a strict view of the real filesystem which means that it won't see files of a package if removed from deps.

the logic within ts_project_worker that is responsible for invalidating module resolution & filesystem cache has a problem. I am working on a fix.

**Comment by alexeagle** [comment]
I'd be very concerned if you really did reproduce this without worker mode!

**Comment by paullewis** [comment]
Update, just so I've logged it really. Per the original point if you have a successful build and remove the types it doesn't fail (and should), but _also_ (as I just discovered) if you have a failing build, add _in the types_ and run `src_typecheck` it still fails. So it's almost like it carries stale build state between runs unless you `bazel clean` between builds.

Not sure if that's adding anything extra to the story, but I wanted to share in case it's helpful.

**Comment by mattem** [comment]
> I'd be very concerned if you really did reproduce this without worker mode!

I can repro a similar issue without worker mode.

**Comment by alexeagle** [comment]
To follow-up, @mattem 's repro is with esbuild, not with tsc.
