### ISSUE TITLE
ts_project transitive closure not propagated through npm_package

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_ts#96]
When using `ts_project`s that are fed into 1p linked `npm_package`s, and accessed through `npm_link_package` targets, further `ts_project`s that depend on these 1p packages do not build properly because transitive deps don't propagate properly through the `npm_package` targets.

Repro:

https://github.com/matthewjh/rules_ts/tree/fork/show-declr-bug

examples/BUILD
```python
npm_link_package(
    name = "node_modules/@myorg/js_lib",
    src = "//examples/js_lib",
    root_package = "examples",
    visibility = ["//examples:__subpackages__"],
)

npm_link_package(
    name = "node_modules/@myorg/ts_lib",
    src = "//examples/ts_lib",
    root_package = "examples",
    visibility = ["//examples:__subpackages__"],
)
```

examples/simple
```python
# Dependencies for all targets in this package
_DEPS = [
    "//examples:node_modules/@myorg/js_lib",
    "//examples:node_modules/@myorg/ts_lib",
    "//examples:node_modules/@types/node"
]

# Type-checks, and emits output to
# bazel-bin/examples/simple/foo.js
# bazel-bin/examples/simple/foo.d.ts
ts_project(
    name = "ts",
    srcs = ["foo.ts"],
    declaration = True,
    # Note, the tsconfig attribute defaults to the tsconfig.json file in this directory.
    # tsconfig = "<default>",
    deps = _DEPS,
    supports_workers = False
)
```

examples/ts-lib
```python
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

_DEPS = [
    "//examples:node_modules/@types/node",
    "//examples:node_modules/date-fns",
]

ts_project(
    name = "ts",
    srcs = ["index.ts"],
    declaration = True,
    # Note, the tsconfig attribute defaults to the tsconfig.json file in this directory.
    # tsconfig = "<default>",
    deps = _DEPS,
    supports_workers = False
)

npm_package(
    name = "ts_lib",
    srcs = ["ts"],
    package = "@myorg/ts_lib",
    visibility = ["//examples:__subpackages__"],
)
```

```shell
matt@Matts-MacBook-Pro rules_ts % bazel build //examples/simple:ts                
INFO: Analyzed target //examples/simple:ts (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/matt/WebstormProjects/rules_ts/examples/simple/BUILD.bazel:14:11: Compiling TypeScript project //examples/simple:ts [tsc -p examples/simple/tsconfig.json] failed: (Exit 2): tsc.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc.sh --project examples/simple/tsconfig.json --outDir examples/simple --rootDir examples/simple --declarationDir examples/simple

Use --sandbox_debug to see verbose messages from the sandbox
examples/node_modules/.aspect_rules_js/@myorg+ts_lib@0.0.0/node_modules/@myorg/ts_lib/index.d.ts(1,65): error TS2307: Cannot find module 'date-fns' or its corresponding type declarations.
Target //examples/simple:ts failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.711s, Critical Path: 1.55s
``` 

What is expected is that the `//examples:node_modules/@myorg/ts_lib` dep on `//examples/simple:ts` populates the sandbox directory with `ts_lib`'s JS and D.TS files (this it does) but also the D.TS files of its dependencies, date-fns (this it does not). As ts_lib produces a D.TS file that refers to a date-fn's typings, without the latter, TSC fails. 

I don't think this is just a matter of transitive D.TS propagation: as ${sandbox_dir}/examples/node_modules contains no date-fns link at all, any downstream build action that needs the JS files of the transitive closure (e.g. a bundling action like esbuild) is also going to fail.

I bumped up rules_js to the latest RC, so this repro includes https://github.com/aspect-build/rules_js/pull/265, which I thought may fix the issue.

cc @gregmagolan

**Comment by gregmagolan** [comment]
This is a tricky one. The current impl requires you to re-specify the direct npm deps from the virtual store in `npm_link_package` if you're linking manually. In theory the deps could be propagated automatically with a new provider. Would require a bit of thought but I think it can be done. I'm camping this week but I'll have some time next week to look at it.

In the meantime, if you use pnpm workspaces and include your first-party package as a workspace, the deps of your first party package will be encoded in the lockfile and included when the package is linked via `npm_link_all_packages`.

An simple example of this is here, https://github.com/aspect-build/rules_js/blob/main/e2e/pnpm_workspace/lib/b/package.json where `@lib/b` is a 1p dep that depends on an npm package `@aspect-test/f`. `rules_js` will expect a npm_package target named `//lib/b:b` (the path of the pnpm workspace). This is here https://github.com/aspect-build/rules_js/blob/main/e2e/pnpm_workspace/lib/b/BUILD.bazel#L6. You can make this include outputs of your `ts_project` target(s) for that 1p package. To link the 1p package where it is used, you can use the `workspace:*` notation in the consuming package.json, https://github.com/aspect-build/rules_js/blob/main/e2e/pnpm_workspace/app/b/package.json#L6.

**Comment by matthewjh** [comment]
Thanks @gregmagolan 

What's interesting about this is that it pushes dependency enumeration out of BUILD files and into package.json. This could certainly have some benefits: e.g. compatibility with the ecosystem and allowing developers to use `pnpm` and package names to add edges to the dep graph rather than bazel labels. There are also some (in my mind) pretty weighty downsides: one of the things I have loved about using Bazel is the precision with which it allows me to specify my dependency graph. I can have separate sets of deps for the impl code and the tests. I am not limited to the simplistic definition in the NPM world of what a dependency "is": I can attach whatever I want onto the build graph: stylesheets, individual files, providers that pass metadata, etc, and have a unified way of conveying all these that is inclusive of NPM packages. So certainly being able to use BUILD files rather than package.json files is much more powerful: it is a superset.

One of my concerns with this was needing to duplicate a library's dependencies between package.json and the BUILD file. However, I see that I can just reference `:node_modules` in the BUILD file, which is a relief.

I will try this out and see how it goes - in the meantime, as you say. I do imagine a lot of people migrating from RNJS will need this though.

**Comment by gregmagolan** [comment]
I chatted about this with @jbedard this morning. One thing you get with specifying the deps of a first-party package in package.json is you can differentiate between `devDependencies` and `dependencies` where both are available for building the package, but only the runtime `dependencies` are propagated to consumers of the package.

Blanket propagating all `deps` forward would be leaky for dependencies that are only needed to build the package. For example, if you have a bundling step and depend on rollup and some rollup plugins. It would make the propagation always-on which may be undesirable for some users. Also, there are some npm deps that might be needed at runtime but not at build time and these would need to be specified as deps and when they change the build actions would be invalidated even when none of the load bearing inputs to the actions changed.

I'm considering the different cases and how to support them all cleanly. Will update here later today or tmr.

**Comment by matthewjh** [comment]
I really like the idea of using `devDependency` vs `dependency` to turn propagation off or on for individual dependencies. It is consistent and I see it being very intuitive for developers new to Bazel.

With RNJS we had some issues with the "always propagate" behaviour, leading us to build rules to anul the NPM providers to switch it off selectively, so I understand what you mean.

BTW, I encountered another use case for propagating a `node_modules` dependency declared programmatically (in a BUILD file) rather than in package.json. We have a macro that provides a batteries-loaded "TypeScript library" with linting, test suite, etc. This calls ts_project with a pre-set tsconfig. Anyway, the tsconfig stipulates that `tslib` will be required at runtime. In this instance, I want to be able to attach `//:node_modules/tslib` to the deps via my macro, and to have that propagated with the library package without listing it in the library's `package.json`. This is a "build implementation detail" dependency rather than a user-facing one, which is why not listing in package.json makes sense. However, I am really warming up to the idea of using `package.json` to convey user/developer-facing dependencies, especially if we can have a distinction between `dev` and `prod` dependencies

**Comment by gregmagolan** [comment]
My refactor branch has the new API working. Rules that want to propagate npm dependencies to be linked as direct deps on downstream npm_package targets should use an attribute named `npm_package_stores`. 

Working example,

https://github.com/aspect-build/rules_js/blob/38aefe54fd2e13e7af74b376e5ac8c07848d25d0/examples/npm_package/packages/pkg_b/BUILD.bazel#L15

**Comment by matthewjh** [comment]
Thanks Greg. I'm traveling/mobile at the moment but will try this out ASAP.

Quick question - can I throw the whole ":node_modules" into this? I am
thinking of having developers manage inter-workspace deps solely via
package JSON so they don't need to touch the BUILD files, as I mentioned
above. Hence, the BUILD file will just refer to the whole node_modules
directory rather than those of individual packages.

Another one: does pnpm lock json itself convey whether a dep is in
dependencies or devDependencies? If so, can the translate_pnpm_lockfile
rule parse these out and auto propagate the "dependencies" but not
"devDependencies" in the package linking rules it instantiates? I assume
this would be built on the infra you've added here. Apologies if your
changes already handle this.

**Comment by alexeagle** [comment]
@matthewjh if we had a gazelle extension to mirror package.json -> BUILD would that work just as well for you?

**Comment by gregmagolan** [comment]
If you use specify your dependencies and devDependencies in the package.json of your first-party library code and use package.json `workspace:*` references with pnpm workspaces to consume them then the code will do what you expect. devDependencies will be available to the library itself to building and only dependencies will be propagated downstream and linked with the library where it is consumed. The difference is encoded in the lock file.

That seems like the preferred and happy path for most users, tho your question of manually propagating was a good one and prompted me to refactor the providers which cleaned up the code quite a bit and will make downstream derivative rules cleaner and more consistent.

Chatted with @alexeagle and he correctly suggested we should just call this `data`. js_library now gets one in my refactor and `ts_project` and other derivative rules that want to be able to specify "runtime" dependencies should as well.

docstring attempts to explain  how to use it,

```
    "data": attr.label_list(
        doc = """Runtime dependencies of this target to add to DefaultInfo runfiles.

        If this list contains linked npm packages or npm package store targets, 'NpmPackageStoreInfo' providers are gathered
        from 'JsInfo' 'npm_package_stores' and 'transitive_npm_package_stores' fields of these targets. For linked npm
        package targets, 'NpmPackageStoreInfo' providers are gathered from the underlying npm_package_store target(s) that
        back the links.

        Gathered 'NpmPackageStoreInfo' providers are used downstream as direct dependencies when linking a downstream
        'npm_package' target with 'npm_link_package'.
        """,
    ),
```

looks like this in practice,

```
js_library(
    name = "lib",
    srcs = [
        "index.js",
        "package.json",
    ],
    data = [
        # runtime dependencies propagate to downstream js_library and npm_link_package (via npm_package) targets
        ":node_modules/acorn",
        ":node_modules/uuid",
    ],
)
```

**Comment by matthewjh** [comment]
@gregmagolan I don't think this is working properly: my original repro fails with the same error. I pushed an updated version here:

https://github.com/matthewjh/rules_ts/tree/fork/declr_bug_new

```shell
bazel build //examples/simple:ts
```

```shell
ERROR: /Users/matt/WebstormProjects/rules_ts/examples/simple/BUILD.bazel:15:11: Compiling TypeScript project //examples/simple:ts [tsc -p examples/simple/tsconfig.json] failed: (Exit 1): tsc_worker.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh @bazel-out/darwin_arm64-fastbuild/bin/examples/simple/foo.js-0.params

examples/node_modules/.aspect_rules_js/@myorg+ts_lib@0.0.0/node_modules/@myorg/ts_lib/index.d.ts(1,65): error TS2307: Cannot find module 'date-fns' or its corresponding type declarations.
```

Query shows that the date-fns is not an input to the action:

```shell
action 'Compiling TypeScript project //examples/simple:ts [tsc -p examples/simple/tsconfig.json]'
  Mnemonic: TsProject
  Target: //examples/simple:ts
  Configuration: darwin_arm64-fastbuild
  Execution platform: @local_config_platform//:host
  ActionKey: eaea31d48864e20ba3b56d14a635d32b9b7e37ee61f3cf177c066bc98086e2e1
  Inputs: [bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/.aspect_rules_js/@myorg+dts_lib@0.0.0/node_modules/@myorg/dts_lib, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/.aspect_rules_js/@myorg+js_lib@0.0.0/node_modules/@myorg/js_lib, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/.aspect_rules_js/@myorg+ts_lib@0.0.0/node_modules/@myorg/ts_lib, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/.aspect_rules_js/@types+node@18.6.1/node_modules/@types/node, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/@myorg/dts_lib, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/@myorg/js_lib, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/@myorg/ts_lib, bazel-out/darwin_arm64-fastbuild/bin/examples/node_modules/@types/node, bazel-out/darwin_arm64-fastbuild/bin/examples/simple/_validate_ts_options.optionsvalid.d.ts, bazel-out/darwin_arm64-fastbuild/bin/examples/simple/foo.ts, bazel-out/darwin_arm64-fastbuild/bin/examples/simple/tsconfig.json, bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh, bazel-out/darwin_arm64-opt-exec-2B5CBBC6/internal/_middlemen/external_Snpm_Utypescript_Stsc_Uworker.sh-runfiles]
  Outputs: [bazel-out/darwin_arm64-fastbuild/bin/examples/simple/foo.d.ts, bazel-out/darwin_arm64-fastbuild/bin/examples/simple/foo.js]
  Environment: [BAZEL_BINDIR=bazel-out/darwin_arm64-fastbuild/bin]
  ExecutionInfo: {supports-workers: 1, worker-key-mnemonic: TsProject}
  Command Line: (exec bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh \
```
