### ISSUE TITLE
add analysis tests for providers passed between js_library/ts_project

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_ts#97]
`DeclarationInfo` from `ts_project` should propagate through `js_library` to be consumed by other `DeclarationInfo`-aware rules (such as more `ts_project` or `js_library` rules). No extra `DeclarationInfo` should be added (example: https://github.com/aspect-build/rules_ts/issues/95)

**Comment by cgrindel** [comment]
@gregmagolan @jbedard I am not sure what the `test` label is meant to mean for this repo. I am trying to consolidate our types to one of the following: bug, documentation, enhancement, question, example. What would you consider this type to be?

**Comment by jbedard** [comment]
@cgrindel we want to add tests to verify some behavior. There's most likely no bug and we just want to verify that and prevent regressions.

**Comment by cgrindel** [comment]
No longer valid.
