### ISSUE TITLE
Non-existent sources don't fail the build

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_ts#99]
Hey, so if we have a `ts_project` and we declare a source file that doesn't exist, everything appears to build correctly even though the source file doesn't exist. This seems a bit odd to me, as I would have expected things to fail given a non-existent input.

So, for example, this:

```bazel
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "src",
    srcs = [
        "baz",
    ],
    tsconfig = "//:tsconfig",
)
```

Here `baz` doesn't exist, and there is no other target in the same package by that name generating TS files.

If it's helpful, I will gladly put a repro repo together for this :)

**Comment by jbedard** [comment]
You don't get the following errors?
```
Error in fail: ts_project target //path:invalid_src is configured to produce no outputs.

This might be because
- you configured it with `noEmit`
- the `srcs` are empty

This is an error because Bazel does not run actions unless their outputs are needed for the requested targets to build.
```

Or if I have a non-existing `.ts` file in the srcs instead of file without a file extension:
```
ERROR: /...path.../BUILD.bazel:3:11: Copying file ...path.../not_found.ts failed: missing input file '//examples/invalid_src:not_found.ts'
ERROR: /...path.../BUILD.bazel:3:11: Copying file ...path.../not_found.ts failed: 1 input file(s) do not exist
ERROR: /...path.../BUILD.bazel:3:11 Copying file ...path.../not_found.ts failed: 1 input file(s) do not exist
```

**Comment by paullewis** [comment]
Not on version 0.10.0, no.

I've made a repo here for you so you can see what I mean: https://github.com/paullewis/repro-rules-ts-issue-99

**Comment by paullewis** [comment]
Ah, so if I bump the `http_archive` in `WORKSPACE` to go to tip-of-tree then I do get the errors you mentioned. Would it be possible to cut a new release then?

**Comment by thesayyn** [comment]
I wonder when and which commit includes the fix for this.

**Comment by jbedard** [comment]
@paullewis we'll publish a release soon, just a couple issues we'd like to fix first.

**Comment by alexeagle** [comment]
https://github.com/aspect-build/rules_ts/releases/tag/v0.11.0 is out, @paullewis do you mind verifying and closing this?

**Comment by paullewis** [comment]
LGTM - closing.
